# Generated by Django 4.2.11 on 2025-08-06 23:20

import crime_report.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crime_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Crime Categories'},
        ),
        migrations.AlterModelOptions(
            name='crimereport',
            options={'ordering': ['-reported_on'], 'permissions': [('can_assign_cases', 'Can assign cases to officers'), ('can_update_status', 'Can update case status'), ('can_view_all_cases', 'Can view all cases')]},
        ),
        migrations.AlterModelOptions(
            name='crimeupdate',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['state', 'city', 'area']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-user_type', 'user__username']},
        ),
        migrations.AlterField(
            model_name='crimecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__user_type__in': ['police', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/', validators=[crime_report.validators.validate_file_extension, crime_report.validators.validate_file_size, crime_report.validators.validate_file_content]),
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='police_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[crime_report.validators.validate_file_extension, crime_report.validators.validate_file_size, crime_report.validators.validate_file_content]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'state', 'area', 'pincode')},
        ),
    ]
